"""create_uniflow_schema

Revision ID: 0bec46ad88a3
Revises: 
Create Date: 2026-09-21 12:57:02.426532
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0bec46ad88a3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uniflow_skill',
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('name = lower(trim(name)) AND length(name) > 0', name=op.f('ck_uniflow_skill_normalized_name')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_uniflow_skill')),
    sa.UniqueConstraint('name', name=op.f('uq_uniflow_skill_name'))
    )
    op.create_table('uniflow_user',
    sa.Column('email', sa.String(length=254), nullable=True),
    sa.Column('password_hash', sa.String(length=60), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('first_name', sa.String(length=100), server_default='', nullable=False),
    sa.Column('last_name', sa.String(length=100), server_default='', nullable=False),
    sa.Column('display_name', sa.String(length=200), server_default='', nullable=False),
    sa.Column('pronouns', sa.String(length=80), server_default='', nullable=False),
    sa.Column('phone', sa.String(length=40), server_default='', nullable=False),
    sa.Column('biography', sa.Text(), server_default='', nullable=False),
    sa.Column('organization', sa.String(length=200), server_default='', nullable=False),
    sa.Column('department', sa.String(length=200), server_default='', nullable=False),
    sa.Column('degree_program', sa.String(length=200), server_default='', nullable=False),
    sa.Column('student_number', sa.String(length=80), nullable=True),
    sa.Column('graduation_date', sa.Date(), nullable=True),
    sa.Column('avatar_storage_key', sa.String(length=512), nullable=True),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('NOT is_active OR password_hash IS NOT NULL', name=op.f('ck_uniflow_user_active_has_password')),
    sa.CheckConstraint('email = lower(trim(email)) AND length(email) > 3', name=op.f('ck_uniflow_user_normalized_email')),
    sa.CheckConstraint('password_hash IS NULL OR length(password_hash) = 60', name=op.f('ck_uniflow_user_bcrypt_hash_length')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_uniflow_user')),
    sa.UniqueConstraint('email', name=op.f('uq_uniflow_user_email')),
    sa.UniqueConstraint('student_number')
    )
    op.create_index('ix_uniflow_user_active_name', 'uniflow_user', ['is_active', 'last_name', 'first_name'], unique=False)
    op.create_table('uniflow_assignment_rule_set',
    sa.Column('family_key', sa.Uuid(), nullable=False),
    sa.Column('revision', sa.Integer(), server_default='1', nullable=False),
    sa.Column('name', sa.String(length=200), server_default='', nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('state', sa.Enum('draft', 'active', 'retired', name='rule_state', native_enum=False, create_constraint=True), server_default='draft', nullable=False),
    sa.Column('min_team_size', sa.Integer(), server_default='3', nullable=False),
    sa.Column('max_team_size', sa.Integer(), server_default='5', nullable=False),
    sa.Column('max_projects_per_student', sa.Integer(), server_default='1', nullable=False),
    sa.Column('require_all_skills', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('enforce_availability', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('allow_unranked_projects', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('preference_opens_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('preference_closes_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('max_projects_per_student >= 1', name=op.f('ck_uniflow_assignment_rule_set_positive_project_limit')),
    sa.CheckConstraint('min_team_size >= 1 AND max_team_size >= min_team_size', name=op.f('ck_uniflow_assignment_rule_set_team_size_range')),
    sa.CheckConstraint('preference_closes_at IS NULL OR preference_opens_at IS NULL OR preference_closes_at > preference_opens_at', name=op.f('ck_uniflow_assignment_rule_set_preference_window')),
    sa.CheckConstraint('revision >= 1', name=op.f('ck_uniflow_assignment_rule_set_positive_revision')),
    sa.ForeignKeyConstraint(['created_by_id'], ['uniflow_user.id'], name=op.f('fk_uniflow_assignment_rule_set_created_by_id_uniflow_user'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_uniflow_assignment_rule_set')),
    sa.UniqueConstraint('family_key', 'revision', name=op.f('uq_uniflow_assignment_rule_set_family_key'))
    )
    op.create_index(op.f('ix_uniflow_assignment_rule_set_created_by_id'), 'uniflow_assignment_rule_set', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_uniflow_assignment_rule_set_family_key'), 'uniflow_assignment_rule_set', ['family_key'], unique=False)
    op.create_index(op.f('ix_uniflow_assignment_rule_set_state'), 'uniflow_assignment_rule_set', ['state'], unique=False)
    op.create_table('uniflow_availability_window',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('weekday', sa.Integer(), server_default='0', nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('kind', sa.Enum('available', 'unavailable', 'preferred', name='availability_kind', native_enum=False, create_constraint=True), server_default='available', nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_until', sa.Date(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('effective_until IS NULL OR effective_from IS NULL OR effective_until >= effective_from', name=op.f('ck_uniflow_availability_window_effective_order')),
    sa.CheckConstraint('end_time > start_time', name=op.f('ck_uniflow_availability_window_time_order')),
    sa.CheckConstraint('weekday BETWEEN 0 AND 6', name=op.f('ck_uniflow_availability_window_weekday_range')),
    sa.ForeignKeyConstraint(['user_id'], ['uniflow_user.id'], name=op.f('fk_uniflow_availability_window_user_id_uniflow_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_uniflow_availability_window'))
    )
    op.create_index('ix_uniflow_availability_user_day', 'uniflow_availability_window', ['user_id', 'weekday'], unique=False)
    op.create_table('uniflow_file',
    sa.Column('storage_key', sa.String(length=512), nullable=True),
    sa.Column('original_filename', sa.String(length=255), server_default='', nullable=False),
    sa.Column('content_type', sa.String(length=160), server_default='application/octet-stream', nullable=False),
    sa.Column('size_bytes', sa.Numeric(precision=20, scale=0), server_default='0', nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('uploaded_by_id', sa.Uuid(), nullable=True),
    sa.Column('state', sa.Enum('pending', 'available', 'quarantined', 'deleted', name='file_state', native_enum=False, create_constraint=True), server_default='pending', nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('sha256 IS NULL OR length(sha256) = 64', name=op.f('ck_uniflow_file_checksum_length')),
    sa.CheckConstraint('size_bytes >= 0', name=op.f('ck_uniflow_file_size_nonnegative')),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['uniflow_user.id'], name=op.f('fk_uniflow_file_uploaded_by_id_uniflow_user'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_uniflow_file')),
    sa.UniqueConstraint('storage_key', name=op.f('uq_uniflow_file_storage_key'))
    )
    op.create_index(op.f('ix_uniflow_file_uploaded_by_id'), 'uniflow_file', ['uploaded_by_id'], unique=False)
    op.create_table('uniflow_milestone_template',
    sa.Column('family_key', sa.Uuid(), nullable=False),
    sa.Column('revision', sa.Integer(), server_default='1', nullable=False),
    sa.Column('name', sa.String(length=200), server_default='', nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('revision >= 1', name=op.f('ck_uniflow_milestone_template_positive_revision')),
    sa.ForeignKeyConstraint(['created_by_id'], ['uniflow_user.id'], name=op.f('fk_uniflow_milestone_template_created_by_id_uniflow_user'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_uniflow_milestone_template')),
    sa.UniqueConstraint('family_key', 'revision', name=op.f('uq_uniflow_milestone_template_family_key'))
    )
    op.create_index(op.f('ix_uniflow_milestone_template_created_by_id'), 'uniflow_milestone_template', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_uniflow_milestone_template_family_key'), 'uniflow_milestone_template', ['family_key'], unique=False)
    op.create_table('uniflow_project',
    sa.Column('title', sa.String(length=240), server_default='', nullable=False),
    sa.Column('summary', sa.Text(), server_default='', nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('sponsor_id', sa.Uuid(), nullable=True),
    sa.Column('advisor_id', sa.Uuid(), nullable=True),
    sa.Column('preferred_min_team_size', sa.Integer(), server_default='3', nullable=False),
    sa.Column('preferred_max_team_size', sa.Integer(), server_default='5', nullable=False),
    sa.Column('proposal_deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lifecycle', sa.Enum('draft', 'submitted', 'under_review', 'changes_requested', 'approved', 'rejected', 'matching', 'active', 'completed', 'cancelled', 'archived', name='project_lifecycle', native_enum=False, create_constraint=True), server_default='draft', nullable=False),
    sa.Column('status', sa.Enum('not_started', 'in_progress', 'on_hold', 'completed', 'cancelled', name='project_status', native_enum=False, create_constraint=True), server_default='not_started', nullable=False),
    sa.Column('health', sa.Enum('unknown', 'on_track', 'at_risk', 'off_track', name='project_health', native_enum=False, create_constraint=True), server_default='unknown', nullable=False),
    sa.Column('review_notes', sa.Text(), server_default='', nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by_id', sa.Uuid(), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by_id', sa.Uuid(), nullable=True),
    sa.Column('approval_notes', sa.Text(), server_default='', nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=True),
    sa.Column('ends_on', sa.Date(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('approved_at IS NULL OR approved_by_id IS NOT NULL', name=op.f('ck_uniflow_project_approval_actor')),
    sa.CheckConstraint('ends_on IS NULL OR starts_on IS NULL OR ends_on >= starts_on', name=op.f('ck_uniflow_project_date_order')),
    sa.CheckConstraint('preferred_min_team_size >= 1 AND preferred_max_team_size >= preferred_min_team_size', name=op.f('ck_uniflow_project_team_size_range')),
    sa.ForeignKeyConstraint(['advisor_id'], ['uniflow_user.id'], name=op.f('fk_uniflow_project_advisor_id_uniflow_user'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['approved_by_id'], ['uniflow_user.id'], name=op.f('fk_uniflow_project_approved_by_id_uniflow_user'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['uniflow_user.id'], name=op.f('fk_uniflow_project_reviewed_by_id_uniflow_user'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sponsor_id'], ['uniflow_user.id'], name=op.f('fk_uniflow_project_sponsor_id_uniflow_user'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_uniflow_project'))
    )
    op.create_index(op.f('ix_uniflow_project_advisor_id'), 'uniflow_project', ['advisor_id'], unique=False)
    op.create_index(op.f('ix_uniflow_project_approved_by_id'), 'uniflow_project', ['approved_by_id'], unique=False)
    op.create_index('ix_uniflow_project_lifecycle_deadline', 'uniflow_project', ['lifecycle', 'proposal_deadline'], unique=False)
    op.create_index(op.f('ix_uniflow_project_reviewed_by_id'), 'uniflow_project', ['reviewed_by_id'], unique=False)
    op.create_index(op.f('ix_uniflow_project_sponsor_id'), 'uniflow_project', ['sponsor_id'], unique=False)
    op.create_index('ix_uniflow_project_status_health', 'uniflow_project', ['status', 'health'], unique=False)
    op.create_table('uniflow_saved_report',
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=200), server_default='', nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('kind', sa.Enum('projects', 'assignments', 'milestones', 'evaluations', 'risks', 'audit', name='report_kind', native_enum=False, create_constraint=True), server_default='projects', nullable=False),
    sa.Column('filters', sa.JSON(), nullable=False),
    sa.Column('columns', sa.JSON(), nullable=False),
    sa.Column('sort_fields', sa.JSON(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['uniflow_user.id'], name=op.f('fk_uniflow_saved_report_owner_id_uniflow_user'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_uniflow_saved_report')),
    sa.UniqueConstraint('owner_id', 'name', name=op.f('uq_uniflow_saved_report_owner_id'))
    )
    op.create_index(op.f('ix_uniflow_saved_report_owner_id'), 'uniflow_saved_report', ['owner_id'], unique=False)
    op.create_table('uniflow_scheduling_constraint',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('timezone', sa.String(length=80), server_default='UTC', nullable=False),
    sa.Column('min_weekly_hours', sa.Numeric(precision=5, scale=2), server_default='0', nullable=False),
    sa.Column('max_weekly_hours', sa.Numeric(precision=5, scale=2), server_default='40', nullable=False),
    sa.Column('max_concurrent_projects', sa.Integer(), server_default='1', nullable=False),
    sa.Column('min_notice_hours', sa.Integer(), server_default='24', nullable=False),
    sa.Column('remote_only', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('notes', sa.Text(), server_default='', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('max_concurrent_projects >= 0 AND min_notice_hours >= 0', name=op.f('ck_uniflow_scheduling_constraint_capacity_range')),
    sa.CheckConstraint('min_weekly_hours >= 0 AND max_weekly_hours >= min_weekly_hours AND max_weekly_hours <= 168', name=op.f('ck_uniflow_scheduling_constraint_hours_range')),
    sa.ForeignKeyConstraint(['user_id'], ['uniflow_user.id'], name=op.f('fk_uniflow_scheduling_constraint_user_id_uniflow_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_uniflow_scheduling_constraint')),
    sa.UniqueConstraint('user_id', name=op.f('uq_uniflow_scheduling_constraint_user_id'))
    )
    op.create_table('uniflow_scheduling_exception',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('kind', sa.Enum('available', 'unavailable', 'preferred', name='exception_kind', native_enum=False, create_constraint=True), server_default='unavailable', nullable=False),
    sa.Column('reason', sa.Text(), server_default='', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('ends_at > starts_at', name=op.f('ck_uniflow_scheduling_exception_time_order')),
    sa.ForeignKeyConstraint(['user_id'], ['uniflow_user.id'], name=op.f('fk_uniflow_scheduling_exception_user_id_uniflow_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_uniflow_scheduling_exception'))
    )
    op.create_index('ix_uniflow_exception_user_start', 'uniflow_scheduling_exception', ['user_id', 'starts_at'], unique=False)
    op.create_table('uniflow_user_role',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('role', sa.Enum('student', 'faculty_advisor', 'sponsor', 'program_administrator', 'system_administrator', name='user_role', native_enum=False, create_constraint=True), server_default='student', nullable=False),
    sa.Column('granted_by_id', sa.Uuid(), nullable=True),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reason', sa.Text(), server_default='', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['granted_by_id'], ['uniflow_user.id'], name=op.f('fk_uniflow_user_role_granted_by_id_uniflow_user'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['uniflow_user.id'], name=op.f('fk_uniflow_user_role_user_id_uniflow_user'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_uniflow_user_role')),
    sa.UniqueConstraint('user_id', 'role', name=op.f('uq_uniflow_user_role_user_id'))
    )
    op.create_index(op.f('ix_uniflow_user_role_granted_by_id'), 'uniflow_user_role', ['granted_by_id'], unique=False)
    op.create_index(op.f('ix_uniflow_user_role_user_id'), 'uniflow_user_role', ['user_id'], unique=False)
    op.create_table('uniflow_user_skill',
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('skill_id', sa.Uuid(), nullable=True),
    sa.Column('proficiency', sa.Integer(), server_default='1', nullable=False),
    sa.Column('years_experience', sa.Numeric(precision=5, scale=2), server_default='0', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('proficiency BETWEEN 1 AND 5', name=op.f('ck_uniflow_user_skill_proficiency_range')),
    sa.CheckConstraint('years_experience >= 0', name=op.f('ck_uniflow_user_skill_experience_nonnegative')),
    sa.ForeignKeyConstraint(['skill_id'], ['uniflow_skill.id'], name=op.f('fk_uniflow_user_skill_skill_id_uniflow_skill'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['uniflow_user.id'], name=op.f('fk_uniflow_user_skill_user_id_uniflow_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_uniflow_user_skill')),
    sa.UniqueConstraint('user_id', 'skill_id', name=op.f('uq_uniflow_user_skill_user_id'))
    )
    op.create_index(op.f('ix_uniflow_user_skill_skill_id'), 'uniflow_user_skill', ['skill_id'], unique=False)
    op.create_index(op.f('ix_uniflow_user_skill_user_id'), 'uniflow_user_skill', ['user_id'], unique=False)
    op.create_table('uniflow_administrator_bootstrap',
    sa.Column('singleton_key', sa.Integer(), server_default='1', nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('role', sa.Enum('student', 'faculty_advisor', 'sponsor', 'program_administrator', 'system_administrator', name='bootstrap_role', native_enum=False, create_constraint=True), server_default='system_administrator', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role = 'system_administrator'", name=op.f('ck_uniflow_administrator_bootstrap_system_role')),
    sa.CheckConstraint('singleton_key = 1', name=op.f('ck_uniflow_administrator_bootstrap_singleton')),
    sa.ForeignKeyConstraint(['user_id', 'role'], ['uniflow_user_role.user_id', 'uniflow_user_role.role'], name=op.f('fk_uniflow_administrator_bootstrap_user_id_uniflow_user_role'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_uniflow_administrator_bootstrap')),
    sa.UniqueConstraint('singleton_key', name=op.f('uq_uniflow_administrator_bootstrap_singleton_key')),
    sa.UniqueConstraint('user_id', name=op.f('uq_uniflow_administrator_bootstrap_user_id'))
    )
    op.create_table('uniflow_assignment_criterion',
    sa.Column('rule_set_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.Enum('student_preference', 'skill_match', 'availability_overlap', 'team_size', 'workload_balance', 'advisor_capacity', name='criterion_kind', native_enum=False, create_constraint=True), server_default='skill_match', nullable=False),
    sa.Column('weight', sa.Numeric(precision=10, scale=4), server_default='1', nullable=False),
    sa.Column('is_hard_constraint', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('is_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('position', sa.Integer(), server_default='1', nullable=False),
    sa.Column('minimum_score', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('position >= 1', name=op.f('ck_uniflow_assignment_criterion_positive_position')),
    sa.CheckConstraint('weight >= 0', name=op.f('ck_uniflow_assignment_criterion_nonnegative_weight')),
    sa.ForeignKeyConstraint(['rule_set_id'], ['uniflow_assignment_rule_set.id'], name=op.f('fk_uniflow_assignment_criterion_rule_set_id_uniflow_assignment_rule_set'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_uniflow_assignment_criterion')),
    sa.UniqueConstraint('rule_set_id', 'kind', name=op.f('uq_uniflow_assignment_criterion_rule_set_id'))
    )
    op.create_index(op.f('ix_uniflow_assignment_criterion_rule_set_id'), 'uniflow_assignment_criterion', ['rule_set_id'], unique=False)
    op.create_table('uniflow_assignment_round',
    sa.Column('name', sa.String(length=200), server_default='', nullable=False),
    sa.Column('rule_set_id', sa.Uuid(), nullable=True),
    sa.Column('state', sa.Enum('proposed', 'confirmed', 'superseded', 'cancelled', name='round_state', native_enum=False, create_constraint=True), server_default='proposed', nullable=False),
    sa.Column('initiated_by_id', sa.Uuid(), nullable=True),
    sa.Column('algorithm_version', sa.String(length=80), server_default='', nullable=False),
    sa.Column('random_seed', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['initiated_by_id'], ['uniflow_user.id'], name=op.f('fk_uniflow_assignment_round_initiated_by_id_uniflow_user'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['rule_set_id'], ['uniflow_assignment_rule_set.id'], name=op.f('fk_uniflow_assignment_round_rule_set_id_uniflow_assignment_rule_set'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_uniflow_assignment_round'))
    )
    op.create_index(op.f('ix_uniflow_assignment_round_initiated_by_id'), 'uniflow_assignment_round', ['initiated_by_id'], unique=False)
    op.create_index(op.f('ix_uniflow_assignment_round_rule_set_id'), 'uniflow_assignment_round', ['rule_set_id'], unique=False)
    op.create_table('uniflow_audit_event',
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=120), server_default='record.created', nullable=False),
    sa.Column('entity_type', sa.String(length=120), server_default='', nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('request_id', sa.Uuid(), nullable=True),
    sa.Column('reason', sa.Text(), server_default='', nullable=False),
    sa.Column('before_values', sa.JSON(), nullable=False),
    sa.Column('after_values', sa.JSON(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('length(trim(action)) > 0', name=op.f('ck_uniflow_audit_event_nonempty_action')),
    sa.ForeignKeyConstraint(['actor_id'], ['uniflow_user.id'], name=op.f('fk_uniflow_audit_event_actor_id_uniflow_user'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['uniflow_project.id'], name=op.f('fk_uniflow_audit_event_project_id_uniflow_project'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_uniflow_audit_event'))
    )
    op.create_index('ix_uniflow_audit_actor_time', 'uniflow_audit_event', ['actor_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_uniflow_audit_event_project_id'), 'uniflow_audit_event', ['project_id'], unique=False)
    op.create_index(op.f('ix_uniflow_audit_event_request_id'), 'uniflow_audit_event', ['request_id'], unique=False)
    op.create_index('ix_uniflow_audit_target_time', 'uniflow_audit_event', ['entity_type', 'entity_id', 'created_at'], unique=False)
    op.create_table('uniflow_meeting',
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('organizer_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=240), server_default='', nullable=False),
    sa.Column('agenda', sa.Text(), server_default='', nullable=False),
    sa.Column('minutes', sa.Text(), server_default='', nullable=False),
    sa.Column('location', sa.String(length=500), server_default='', nullable=False),
    sa.Column('conference_url', sa.String(length=2048), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('state', sa.Enum('scheduled', 'completed', 'cancelled', name='meeting_state', native_enum=False, create_constraint=True), server_default='scheduled', nullable=False),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancellation_reason', sa.Text(), server_default='', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('ends_at > starts_at', name=op.f('ck_uniflow_meeting_time_order')),
    sa.ForeignKeyConstraint(['organizer_id'], ['uniflow_user.id'], name=op.f('fk_uniflow_meeting_organizer_id_uniflow_user'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['uniflow_project.id'], name=op.f('fk_uniflow_meeting_project_id_uniflow_project'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_uniflow_meeting'))
    )
    op.create_index(op.f('ix_uniflow_meeting_organizer_id'), 'uniflow_meeting', ['organizer_id'], unique=False)
    op.create_index('ix_uniflow_meeting_project_start', 'uniflow_meeting', ['project_id', 'starts_at'], unique=False)
    op.create_table('uniflow_milestone_template_item',
    sa.Column('template_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=240), server_default='', nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('acceptance_criteria', sa.Text(), server_default='', nullable=False),
    sa.Column('position', sa.Integer(), server_default='1', nullable=False),
    sa.Column('due_offset_days', sa.Integer(), server_default='0', nullable=False),
    sa.Column('requires_deliverable', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('weight', sa.Numeric(precision=10, scale=4), server_default='1', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('position >= 1 AND due_offset_days >= 0', name=op.f('ck_uniflow_milestone_template_item_position_offset_range')),
    sa.CheckConstraint('weight >= 0', name=op.f('ck_uniflow_milestone_template_item_weight_nonnegative')),
    sa.ForeignKeyConstraint(['template_id'], ['uniflow_milestone_template.id'], name=op.f('fk_uniflow_milestone_template_item_template_id_uniflow_milestone_template'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_uniflow_milestone_template_item')),
    sa.UniqueConstraint('template_id', 'position', name=op.f('uq_uniflow_milestone_template_item_template_id'))
    )
    op.create_index(op.f('ix_uniflow_milestone_template_item_template_id'), 'uniflow_milestone_template_item', ['template_id'], unique=False)
    op.create_table('uniflow_notification',
    sa.Column('recipient_id', sa.Uuid(), nullable=True),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.Enum('general', 'project_review', 'assignment', 'milestone_due', 'deliverable_review', 'meeting', 'risk_issue', name='notification_kind', native_enum=False, create_constraint=True), server_default='general', nullable=False),
    sa.Column('title', sa.String(length=240), server_default='', nullable=False),
    sa.Column('body', sa.Text(), server_default='', nullable=False),
    sa.Column('action_path', sa.String(length=512), nullable=True),
    sa.Column('deduplication_key', sa.String(length=200), nullable=True),
    sa.Column('processing_state', sa.Enum('pending', 'processing', 'delivered', 'failed', 'cancelled', name='notification_processing', native_enum=False, create_constraint=True), server_default='pending', nullable=False),
    sa.Column('read_state', sa.Enum('unread', 'read', 'dismissed', name='notification_read', native_enum=False, create_constraint=True), server_default='unread', nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('max_attempts', sa.Integer(), server_default='5', nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lock_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('lock_token', sa.Uuid(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dismissed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("processing_state != 'processing' OR (locked_at IS NOT NULL AND lock_token IS NOT NULL)", name=op.f('ck_uniflow_notification_processing_lease')),
    sa.CheckConstraint("read_state != 'read' OR read_at IS NOT NULL", name=op.f('ck_uniflow_notification_read_timestamp')),
    sa.CheckConstraint('attempts >= 0 AND max_attempts >= 1', name=op.f('ck_uniflow_notification_attempt_range')),
    sa.ForeignKeyConstraint(['actor_id'], ['uniflow_user.id'], name=op.f('fk_uniflow_notification_actor_id_uniflow_user'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['uniflow_project.id'], name=op.f('fk_uniflow_notification_project_id_uniflow_project'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['recipient_id'], ['uniflow_user.id'], name=op.f('fk_uniflow_notification_recipient_id_uniflow_user'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_uniflow_notification')),
    sa.UniqueConstraint('recipient_id', 'deduplication_key', name=op.f('uq_uniflow_notification_recipient_id'))
    )
    op.create_index(op.f('ix_uniflow_notification_actor_id'), 'uniflow_notification', ['actor_id'], unique=False)
    op.create_index('ix_uniflow_notification_inbox', 'uniflow_notification', ['recipient_id', 'read_state', 'created_at'], unique=False)
    op.create_index(op.f('ix_uniflow_notification_lock_expires_at'), 'uniflow_notification', ['lock_expires_at'], unique=False)
    op.create_index(op.f('ix_uniflow_notification_project_id'), 'uniflow_notification', ['project_id'], unique=False)
    op.create_index('ix_uniflow_notification_queue', 'uniflow_notification', ['processing_state', 'scheduled_at', 'next_attempt_at'], unique=False)
    op.create_table('uniflow_project_document',
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('file_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=240), server_default='', nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('withdrawn_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['uniflow_file.id'], name=op.f('fk_uniflow_project_document_file_id_uniflow_file'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['uniflow_project.id'], name=op.f('fk_uniflow_project_document_project_id_uniflow_project'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_uniflow_project_document')),
    sa.UniqueConstraint('project_id', 'file_id', name=op.f('uq_uniflow_project_document_project_id'))
    )
    op.create_index(op.f('ix_uniflow_project_document_file_id'), 'uniflow_project_document', ['file_id'], unique=False)
    op.create_index(op.f('ix_uniflow_project_document_project_id'), 'uniflow_project_document', ['project_id'], unique=False)
    op.create_table('uniflow_project_objective',
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('position', sa.Integer(), server_default='1', nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('success_criteria', sa.Text(), server_default='', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('position >= 1', name=op.f('ck_uniflow_project_objective_positive_position')),
    sa.ForeignKeyConstraint(['project_id'], ['uniflow_project.id'], name=op.f('fk_uniflow_project_objective_project_id_uniflow_project'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_uniflow_project_objective')),
    sa.UniqueConstraint('project_id', 'position', name=op.f('uq_uniflow_project_objective_project_id'))
    )
    op.create_index(op.f('ix_uniflow_project_objective_project_id'), 'uniflow_project_objective', ['project_id'], unique=False)
    op.create_table('uniflow_project_skill',
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('skill_id', sa.Uuid(), nullable=True),
    sa.Column('minimum_proficiency', sa.Integer(), server_default='1', nullable=False),
    sa.Column('is_required', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('weight', sa.Numeric(precision=10, scale=4), server_default='1', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('minimum_proficiency BETWEEN 1 AND 5', name=op.f('ck_uniflow_project_skill_proficiency_range')),
    sa.CheckConstraint('weight >= 0', name=op.f('ck_uniflow_project_skill_nonnegative_weight')),
    sa.ForeignKeyConstraint(['project_id'], ['uniflow_project.id'], name=op.f('fk_uniflow_project_skill_project_id_uniflow_project'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['uniflow_skill.id'], name=op.f('fk_uniflow_project_skill_skill_id_uniflow_skill'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_uniflow_project_skill')),
    sa.UniqueConstraint('project_id', 'skill_id', name=op.f('uq_uniflow_project_skill_project_id'))
    )
    op.create_index(op.f('ix_uniflow_project_skill_project_id'), 'uniflow_project_skill', ['project_id'], unique=False)
    op.create_index(op.f('ix_uniflow_project_skill_skill_id'), 'uniflow_project_skill', ['skill_id'], unique=False)
    op.create_table('uniflow_report_export',
    sa.Column('saved_report_id', sa.Uuid(), nullable=True),
    sa.Column('requested_by_id', sa.Uuid(), nullable=True),
    sa.Column('file_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.Enum('projects', 'assignments', 'milestones', 'evaluations', 'risks', 'audit', name='export_report_kind', native_enum=False, create_constraint=True), server_default='projects', nullable=False),
    sa.Column('format', sa.Enum('csv', 'xlsx', 'pdf', 'json', name='export_format', native_enum=False, create_constraint=True), server_default='csv', nullable=False),
    sa.Column('state', sa.Enum('queued', 'processing', 'ready', 'failed', 'expired', name='export_state', native_enum=False, create_constraint=True), server_default='queued', nullable=False),
    sa.Column('filters_snapshot', sa.JSON(), nullable=False),
    sa.Column('columns_snapshot', sa.JSON(), nullable=False),
    sa.Column('sort_snapshot', sa.JSON(), nullable=False),
    sa.Column('source_as_of', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("state != 'ready' OR (file_id IS NOT NULL AND completed_at IS NOT NULL)", name=op.f('ck_uniflow_report_export_ready_artifact')),
    sa.CheckConstraint('row_count IS NULL OR row_count >= 0', name=op.f('ck_uniflow_report_export_row_count_nonnegative')),
    sa.ForeignKeyConstraint(['file_id'], ['uniflow_file.id'], name=op.f('fk_uniflow_report_export_file_id_uniflow_file'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['requested_by_id'], ['uniflow_user.id'], name=op.f('fk_uniflow_report_export_requested_by_id_uniflow_user'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['saved_report_id'], ['uniflow_saved_report.id'], name=op.f('fk_uniflow_report_export_saved_report_id_uniflow_saved_report'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_uniflow_report_export'))
    )
    op.create_index('ix_uniflow_export_state_created', 'uniflow_report_export', ['state', 'created_at'], unique=False)
    op.create_index(op.f('ix_uniflow_report_export_expires_at'), 'uniflow_report_export', ['expires_at'], unique=False)
    op.create_index(op.f('ix_uniflow_report_export_file_id'), 'uniflow_report_export', ['file_id'], unique=False)
    op.create_index(op.f('ix_uniflow_report_export_requested_by_id'), 'uniflow_report_export', ['requested_by_id'], unique=False)
    op.create_index(op.f('ix_uniflow_report_export_saved_report_id'), 'uniflow_report_export', ['saved_report_id'], unique=False)
    op.create_table('uniflow_risk_issue',
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('reported_by_id', sa.Uuid(), nullable=True),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('kind', sa.Enum('risk', 'issue', name='issue_kind', native_enum=False, create_constraint=True), server_default='risk', nullable=False),
    sa.Column('severity', sa.Enum('low', 'medium', 'high', 'critical', name='issue_severity', native_enum=False, create_constraint=True), server_default='medium', nullable=False),
    sa.Column('state', sa.Enum('open', 'mitigating', 'resolved', 'closed', 'accepted', name='issue_state', native_enum=False, create_constraint=True), server_default='open', nullable=False),
    sa.Column('title', sa.String(length=240), server_default='', nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('likelihood', sa.Integer(), server_default='3', nullable=False),
    sa.Column('impact', sa.Integer(), server_default='3', nullable=False),
    sa.Column('mitigation_plan', sa.Text(), server_default='', nullable=False),
    sa.Column('resolution', sa.Text(), server_default='', nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by_id', sa.Uuid(), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('likelihood BETWEEN 1 AND 5 AND impact BETWEEN 1 AND 5', name=op.f('ck_uniflow_risk_issue_risk_score_range')),
    sa.ForeignKeyConstraint(['owner_id'], ['uniflow_user.id'], name=op.f('fk_uniflow_risk_issue_owner_id_uniflow_user'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['uniflow_project.id'], name=op.f('fk_uniflow_risk_issue_project_id_uniflow_project'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reported_by_id'], ['uniflow_user.id'], name=op.f('fk_uniflow_risk_issue_reported_by_id_uniflow_user'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['resolved_by_id'], ['uniflow_user.id'], name=op.f('fk_uniflow_risk_issue_resolved_by_id_uniflow_user'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_uniflow_risk_issue'))
    )
    op.create_index(op.f('ix_uniflow_risk_issue_due_at'), 'uniflow_risk_issue', ['due_at'], unique=False)
    op.create_index(op.f('ix_uniflow_risk_issue_owner_id'), 'uniflow_risk_issue', ['owner_id'], unique=False)
    op.create_index(op.f('ix_uniflow_risk_issue_reported_by_id'), 'uniflow_risk_issue', ['reported_by_id'], unique=False)
    op.create_index(op.f('ix_uniflow_risk_issue_resolved_by_id'), 'uniflow_risk_issue', ['resolved_by_id'], unique=False)
    op.create_index('ix_uniflow_risk_project_state', 'uniflow_risk_issue', ['project_id', 'state', 'severity'], unique=False)
    op.create_table('uniflow_meeting_attendee',
    sa.Column('meeting_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('attendance', sa.Enum('invited', 'accepted', 'tentative', 'declined', 'attended', 'absent', name='attendance_state', native_enum=False, create_constraint=True), server_default='invited', nullable=False),
    sa.Column('is_required', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['uniflow_meeting.id'], name=op.f('fk_uniflow_meeting_attendee_meeting_id_uniflow_meeting'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['uniflow_user.id'], name=op.f('fk_uniflow_meeting_attendee_user_id_uniflow_user'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_uniflow_meeting_attendee')),
    sa.UniqueConstraint('meeting_id', 'user_id', name=op.f('uq_uniflow_meeting_attendee_meeting_id'))
    )
    op.create_index(op.f('ix_uniflow_meeting_attendee_meeting_id'), 'uniflow_meeting_attendee', ['meeting_id'], unique=False)
    op.create_index(op.f('ix_uniflow_meeting_attendee_user_id'), 'uniflow_meeting_attendee', ['user_id'], unique=False)
    op.create_table('uniflow_project_milestone',
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('template_item_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=240), server_default='', nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('acceptance_criteria', sa.Text(), server_default='', nullable=False),
    sa.Column('position', sa.Integer(), server_default='1', nullable=False),
    sa.Column('weight', sa.Numeric(precision=10, scale=4), server_default='1', nullable=False),
    sa.Column('requires_deliverable', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('state', sa.Enum('not_started', 'in_progress', 'submitted', 'changes_requested', 'accepted', 'waived', name='milestone_state', native_enum=False, create_constraint=True), server_default='not_started', nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('original_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('accepted_by_id', sa.Uuid(), nullable=True),
    sa.Column('owner_id', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('position >= 1 AND weight >= 0', name=op.f('ck_uniflow_project_milestone_position_weight_range')),
    sa.ForeignKeyConstraint(['accepted_by_id'], ['uniflow_user.id'], name=op.f('fk_uniflow_project_milestone_accepted_by_id_uniflow_user'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['owner_id'], ['uniflow_user.id'], name=op.f('fk_uniflow_project_milestone_owner_id_uniflow_user'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['uniflow_project.id'], name=op.f('fk_uniflow_project_milestone_project_id_uniflow_project'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['template_item_id'], ['uniflow_milestone_template_item.id'], name=op.f('fk_uniflow_project_milestone_template_item_id_uniflow_milestone_template_item'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_uniflow_project_milestone')),
    sa.UniqueConstraint('id', 'project_id', name=op.f('uq_uniflow_project_milestone_id')),
    sa.UniqueConstraint('project_id', 'position', name=op.f('uq_uniflow_project_milestone_project_id'))
    )
    op.create_index('ix_uniflow_milestone_state_due', 'uniflow_project_milestone', ['state', 'due_at'], unique=False)
    op.create_index(op.f('ix_uniflow_project_milestone_accepted_by_id'), 'uniflow_project_milestone', ['accepted_by_id'], unique=False)
    op.create_index(op.f('ix_uniflow_project_milestone_owner_id'), 'uniflow_project_milestone', ['owner_id'], unique=False)
    op.create_index(op.f('ix_uniflow_project_milestone_project_id'), 'uniflow_project_milestone', ['project_id'], unique=False)
    op.create_index(op.f('ix_uniflow_project_milestone_template_item_id'), 'uniflow_project_milestone', ['template_item_id'], unique=False)
    op.create_table('uniflow_student_preference',
    sa.Column('round_id', sa.Uuid(), nullable=True),
    sa.Column('student_id', sa.Uuid(), nullable=True),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('rank', sa.Integer(), server_default='1', nullable=False),
    sa.Column('rationale', sa.Text(), server_default='', nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rank >= 1', name=op.f('ck_uniflow_student_preference_positive_rank')),
    sa.ForeignKeyConstraint(['project_id'], ['uniflow_project.id'], name=op.f('fk_uniflow_student_preference_project_id_uniflow_project'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['round_id'], ['uniflow_assignment_round.id'], name=op.f('fk_uniflow_student_preference_round_id_uniflow_assignment_round'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['uniflow_user.id'], name=op.f('fk_uniflow_student_preference_student_id_uniflow_user'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_uniflow_student_preference')),
    sa.UniqueConstraint('round_id', 'student_id', 'project_id', name='uq_preference_round_student_project'),
    sa.UniqueConstraint('round_id', 'student_id', 'rank', name='uq_preference_round_student_rank')
    )
    op.create_index(op.f('ix_uniflow_student_preference_project_id'), 'uniflow_student_preference', ['project_id'], unique=False)
    op.create_index(op.f('ix_uniflow_student_preference_round_id'), 'uniflow_student_preference', ['round_id'], unique=False)
    op.create_index(op.f('ix_uniflow_student_preference_student_id'), 'uniflow_student_preference', ['student_id'], unique=False)
    op.create_table('uniflow_team_assignment',
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('round_id', sa.Uuid(), nullable=True),
    sa.Column('advisor_id', sa.Uuid(), nullable=True),
    sa.Column('name', sa.String(length=200), server_default='', nullable=False),
    sa.Column('state', sa.Enum('proposed', 'confirmed', 'superseded', 'cancelled', name='assignment_state', native_enum=False, create_constraint=True), server_default='proposed', nullable=False),
    sa.Column('score', sa.Numeric(precision=14, scale=4), nullable=True),
    sa.Column('assigned_by_id', sa.Uuid(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_manual_override', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('overridden_by_id', sa.Uuid(), nullable=True),
    sa.Column('overridden_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('override_reason', sa.Text(), server_default='', nullable=False),
    sa.Column('supersedes_id', sa.Uuid(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('NOT is_manual_override OR (overridden_by_id IS NOT NULL AND overridden_at IS NOT NULL AND length(trim(override_reason)) > 0)', name=op.f('ck_uniflow_team_assignment_override_metadata')),
    sa.ForeignKeyConstraint(['advisor_id'], ['uniflow_user.id'], name=op.f('fk_uniflow_team_assignment_advisor_id_uniflow_user'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['uniflow_user.id'], name=op.f('fk_uniflow_team_assignment_assigned_by_id_uniflow_user'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['overridden_by_id'], ['uniflow_user.id'], name=op.f('fk_uniflow_team_assignment_overridden_by_id_uniflow_user'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['uniflow_project.id'], name=op.f('fk_uniflow_team_assignment_project_id_uniflow_project'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['round_id'], ['uniflow_assignment_round.id'], name=op.f('fk_uniflow_team_assignment_round_id_uniflow_assignment_round'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['supersedes_id'], ['uniflow_team_assignment.id'], name=op.f('fk_uniflow_team_assignment_supersedes_id_uniflow_team_assignment'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_uniflow_team_assignment')),
    sa.UniqueConstraint('id', 'project_id', name=op.f('uq_uniflow_team_assignment_id')),
    sa.UniqueConstraint('round_id', 'project_id', name=op.f('uq_uniflow_team_assignment_round_id'))
    )
    op.create_index(op.f('ix_uniflow_team_assignment_advisor_id'), 'uniflow_team_assignment', ['advisor_id'], unique=False)
    op.create_index(op.f('ix_uniflow_team_assignment_assigned_by_id'), 'uniflow_team_assignment', ['assigned_by_id'], unique=False)
    op.create_index(op.f('ix_uniflow_team_assignment_overridden_by_id'), 'uniflow_team_assignment', ['overridden_by_id'], unique=False)
    op.create_index(op.f('ix_uniflow_team_assignment_project_id'), 'uniflow_team_assignment', ['project_id'], unique=False)
    op.create_index(op.f('ix_uniflow_team_assignment_round_id'), 'uniflow_team_assignment', ['round_id'], unique=False)
    op.create_index(op.f('ix_uniflow_team_assignment_state'), 'uniflow_team_assignment', ['state'], unique=False)
    op.create_index(op.f('ix_uniflow_team_assignment_supersedes_id'), 'uniflow_team_assignment', ['supersedes_id'], unique=False)
    op.create_table('uniflow_deliverable',
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('milestone_id', sa.Uuid(), nullable=True),
    sa.Column('title', sa.String(length=240), server_default='', nullable=False),
    sa.Column('description', sa.Text(), server_default='', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['milestone_id', 'project_id'], ['uniflow_project_milestone.id', 'uniflow_project_milestone.project_id'], name=op.f('fk_uniflow_deliverable_milestone_id_uniflow_project_milestone'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['uniflow_project.id'], name=op.f('fk_uniflow_deliverable_project_id_uniflow_project'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_uniflow_deliverable')),
    sa.UniqueConstraint('id', 'project_id', name=op.f('uq_uniflow_deliverable_id'))
    )
    op.create_index(op.f('ix_uniflow_deliverable_milestone_id'), 'uniflow_deliverable', ['milestone_id'], unique=False)
    op.create_index(op.f('ix_uniflow_deliverable_project_id'), 'uniflow_deliverable', ['project_id'], unique=False)
    op.create_table('uniflow_team_membership',
    sa.Column('team_id', sa.Uuid(), nullable=True),
    sa.Column('student_id', sa.Uuid(), nullable=True),
    sa.Column('role', sa.Enum('member', 'lead', name='member_role', native_enum=False, create_constraint=True), server_default='member', nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('left_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('assigned_by_id', sa.Uuid(), nullable=True),
    sa.Column('is_manual_override', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('overridden_by_id', sa.Uuid(), nullable=True),
    sa.Column('overridden_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('override_reason', sa.Text(), server_default='', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('NOT is_manual_override OR (overridden_by_id IS NOT NULL AND overridden_at IS NOT NULL AND length(trim(override_reason)) > 0)', name=op.f('ck_uniflow_team_membership_override_metadata')),
    sa.CheckConstraint('left_at IS NULL OR left_at >= joined_at', name=op.f('ck_uniflow_team_membership_membership_dates')),
    sa.ForeignKeyConstraint(['assigned_by_id'], ['uniflow_user.id'], name=op.f('fk_uniflow_team_membership_assigned_by_id_uniflow_user'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['overridden_by_id'], ['uniflow_user.id'], name=op.f('fk_uniflow_team_membership_overridden_by_id_uniflow_user'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['uniflow_user.id'], name=op.f('fk_uniflow_team_membership_student_id_uniflow_user'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['team_id'], ['uniflow_team_assignment.id'], name=op.f('fk_uniflow_team_membership_team_id_uniflow_team_assignment'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_uniflow_team_membership')),
    sa.UniqueConstraint('team_id', 'student_id', name=op.f('uq_uniflow_team_membership_team_id'))
    )
    op.create_index(op.f('ix_uniflow_team_membership_assigned_by_id'), 'uniflow_team_membership', ['assigned_by_id'], unique=False)
    op.create_index(op.f('ix_uniflow_team_membership_overridden_by_id'), 'uniflow_team_membership', ['overridden_by_id'], unique=False)
    op.create_index(op.f('ix_uniflow_team_membership_student_id'), 'uniflow_team_membership', ['student_id'], unique=False)
    op.create_index(op.f('ix_uniflow_team_membership_team_id'), 'uniflow_team_membership', ['team_id'], unique=False)
    op.create_table('uniflow_deliverable_submission',
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('deliverable_id', sa.Uuid(), nullable=True),
    sa.Column('team_id', sa.Uuid(), nullable=True),
    sa.Column('revision', sa.Integer(), server_default='1', nullable=False),
    sa.Column('state', sa.Enum('draft', 'submitted', 'under_review', 'changes_requested', 'accepted', 'withdrawn', name='submission_state', native_enum=False, create_constraint=True), server_default='draft', nullable=False),
    sa.Column('submitted_by_id', sa.Uuid(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('content', sa.Text(), server_default='', nullable=False),
    sa.Column('revision_notes', sa.Text(), server_default='', nullable=False),
    sa.Column('reviewed_by_id', sa.Uuid(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_notes', sa.Text(), server_default='', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('revision >= 1', name=op.f('ck_uniflow_deliverable_submission_positive_revision')),
    sa.ForeignKeyConstraint(['deliverable_id', 'project_id'], ['uniflow_deliverable.id', 'uniflow_deliverable.project_id'], name=op.f('fk_uniflow_deliverable_submission_deliverable_id_uniflow_deliverable'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['uniflow_project.id'], name=op.f('fk_uniflow_deliverable_submission_project_id_uniflow_project'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['uniflow_user.id'], name=op.f('fk_uniflow_deliverable_submission_reviewed_by_id_uniflow_user'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['submitted_by_id'], ['uniflow_user.id'], name=op.f('fk_uniflow_deliverable_submission_submitted_by_id_uniflow_user'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['team_id', 'project_id'], ['uniflow_team_assignment.id', 'uniflow_team_assignment.project_id'], name=op.f('fk_uniflow_deliverable_submission_team_id_uniflow_team_assignment'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_uniflow_deliverable_submission')),
    sa.UniqueConstraint('deliverable_id', 'revision', name=op.f('uq_uniflow_deliverable_submission_deliverable_id')),
    sa.UniqueConstraint('id', 'project_id', name=op.f('uq_uniflow_deliverable_submission_id'))
    )
    op.create_index(op.f('ix_uniflow_deliverable_submission_deliverable_id'), 'uniflow_deliverable_submission', ['deliverable_id'], unique=False)
    op.create_index(op.f('ix_uniflow_deliverable_submission_project_id'), 'uniflow_deliverable_submission', ['project_id'], unique=False)
    op.create_index(op.f('ix_uniflow_deliverable_submission_reviewed_by_id'), 'uniflow_deliverable_submission', ['reviewed_by_id'], unique=False)
    op.create_index(op.f('ix_uniflow_deliverable_submission_submitted_by_id'), 'uniflow_deliverable_submission', ['submitted_by_id'], unique=False)
    op.create_index(op.f('ix_uniflow_deliverable_submission_team_id'), 'uniflow_deliverable_submission', ['team_id'], unique=False)
    op.create_index('ix_uniflow_submission_state_time', 'uniflow_deliverable_submission', ['state', 'submitted_at'], unique=False)
    op.create_table('uniflow_advisor_evaluation',
    sa.Column('evaluation_key', sa.Uuid(), nullable=False),
    sa.Column('revision', sa.Integer(), server_default='1', nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('advisor_id', sa.Uuid(), nullable=True),
    sa.Column('student_id', sa.Uuid(), nullable=True),
    sa.Column('milestone_id', sa.Uuid(), nullable=True),
    sa.Column('submission_id', sa.Uuid(), nullable=True),
    sa.Column('score', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('maximum_score', sa.Numeric(precision=8, scale=2), server_default='100', nullable=False),
    sa.Column('comments', sa.Text(), server_default='', nullable=False),
    sa.Column('rubric_name', sa.String(length=200), server_default='', nullable=False),
    sa.Column('finalized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('maximum_score > 0 AND revision >= 1', name=op.f('ck_uniflow_advisor_evaluation_maximum_revision_range')),
    sa.CheckConstraint('score IS NULL OR (score >= 0 AND score <= maximum_score)', name=op.f('ck_uniflow_advisor_evaluation_score_range')),
    sa.ForeignKeyConstraint(['advisor_id'], ['uniflow_user.id'], name=op.f('fk_uniflow_advisor_evaluation_advisor_id_uniflow_user'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['milestone_id', 'project_id'], ['uniflow_project_milestone.id', 'uniflow_project_milestone.project_id'], name=op.f('fk_uniflow_advisor_evaluation_milestone_id_uniflow_project_milestone'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['uniflow_project.id'], name=op.f('fk_uniflow_advisor_evaluation_project_id_uniflow_project'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['student_id'], ['uniflow_user.id'], name=op.f('fk_uniflow_advisor_evaluation_student_id_uniflow_user'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['submission_id', 'project_id'], ['uniflow_deliverable_submission.id', 'uniflow_deliverable_submission.project_id'], name=op.f('fk_uniflow_advisor_evaluation_submission_id_uniflow_deliverable_submission'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_uniflow_advisor_evaluation')),
    sa.UniqueConstraint('evaluation_key', 'revision', name=op.f('uq_uniflow_advisor_evaluation_evaluation_key'))
    )
    op.create_index(op.f('ix_uniflow_advisor_evaluation_advisor_id'), 'uniflow_advisor_evaluation', ['advisor_id'], unique=False)
    op.create_index(op.f('ix_uniflow_advisor_evaluation_milestone_id'), 'uniflow_advisor_evaluation', ['milestone_id'], unique=False)
    op.create_index(op.f('ix_uniflow_advisor_evaluation_project_id'), 'uniflow_advisor_evaluation', ['project_id'], unique=False)
    op.create_index(op.f('ix_uniflow_advisor_evaluation_student_id'), 'uniflow_advisor_evaluation', ['student_id'], unique=False)
    op.create_index(op.f('ix_uniflow_advisor_evaluation_submission_id'), 'uniflow_advisor_evaluation', ['submission_id'], unique=False)
    op.create_table('uniflow_sponsor_feedback',
    sa.Column('feedback_key', sa.Uuid(), nullable=False),
    sa.Column('revision', sa.Integer(), server_default='1', nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=True),
    sa.Column('sponsor_id', sa.Uuid(), nullable=True),
    sa.Column('milestone_id', sa.Uuid(), nullable=True),
    sa.Column('submission_id', sa.Uuid(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('comments', sa.Text(), server_default='', nullable=False),
    sa.Column('requested_changes', sa.Text(), server_default='', nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rating IS NULL OR rating BETWEEN 1 AND 5', name=op.f('ck_uniflow_sponsor_feedback_rating_range')),
    sa.CheckConstraint('revision >= 1', name=op.f('ck_uniflow_sponsor_feedback_positive_revision')),
    sa.ForeignKeyConstraint(['milestone_id', 'project_id'], ['uniflow_project_milestone.id', 'uniflow_project_milestone.project_id'], name=op.f('fk_uniflow_sponsor_feedback_milestone_id_uniflow_project_milestone'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['project_id'], ['uniflow_project.id'], name=op.f('fk_uniflow_sponsor_feedback_project_id_uniflow_project'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sponsor_id'], ['uniflow_user.id'], name=op.f('fk_uniflow_sponsor_feedback_sponsor_id_uniflow_user'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['submission_id', 'project_id'], ['uniflow_deliverable_submission.id', 'uniflow_deliverable_submission.project_id'], name=op.f('fk_uniflow_sponsor_feedback_submission_id_uniflow_deliverable_submission'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_uniflow_sponsor_feedback')),
    sa.UniqueConstraint('feedback_key', 'revision', name=op.f('uq_uniflow_sponsor_feedback_feedback_key'))
    )
    op.create_index(op.f('ix_uniflow_sponsor_feedback_milestone_id'), 'uniflow_sponsor_feedback', ['milestone_id'], unique=False)
    op.create_index(op.f('ix_uniflow_sponsor_feedback_project_id'), 'uniflow_sponsor_feedback', ['project_id'], unique=False)
    op.create_index(op.f('ix_uniflow_sponsor_feedback_sponsor_id'), 'uniflow_sponsor_feedback', ['sponsor_id'], unique=False)
    op.create_index(op.f('ix_uniflow_sponsor_feedback_submission_id'), 'uniflow_sponsor_feedback', ['submission_id'], unique=False)
    op.create_table('uniflow_submission_file',
    sa.Column('submission_id', sa.Uuid(), nullable=True),
    sa.Column('file_id', sa.Uuid(), nullable=True),
    sa.Column('caption', sa.String(length=240), server_default='', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['uniflow_file.id'], name=op.f('fk_uniflow_submission_file_file_id_uniflow_file'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['submission_id'], ['uniflow_deliverable_submission.id'], name=op.f('fk_uniflow_submission_file_submission_id_uniflow_deliverable_submission'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_uniflow_submission_file')),
    sa.UniqueConstraint('submission_id', 'file_id', name=op.f('uq_uniflow_submission_file_submission_id'))
    )
    op.create_index(op.f('ix_uniflow_submission_file_file_id'), 'uniflow_submission_file', ['file_id'], unique=False)
    op.create_index(op.f('ix_uniflow_submission_file_submission_id'), 'uniflow_submission_file', ['submission_id'], unique=False)
    op.create_table('uniflow_evaluation_criterion_score',
    sa.Column('evaluation_id', sa.Uuid(), nullable=True),
    sa.Column('criterion', sa.String(length=200), server_default='', nullable=False),
    sa.Column('score', sa.Numeric(precision=8, scale=2), server_default='0', nullable=False),
    sa.Column('maximum_score', sa.Numeric(precision=8, scale=2), server_default='100', nullable=False),
    sa.Column('weight', sa.Numeric(precision=10, scale=4), server_default='1', nullable=False),
    sa.Column('comments', sa.Text(), server_default='', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('maximum_score > 0 AND score >= 0 AND score <= maximum_score AND weight >= 0', name=op.f('ck_uniflow_evaluation_criterion_score_score_weight_range')),
    sa.ForeignKeyConstraint(['evaluation_id'], ['uniflow_advisor_evaluation.id'], name=op.f('fk_uniflow_evaluation_criterion_score_evaluation_id_uniflow_advisor_evaluation'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_uniflow_evaluation_criterion_score')),
    sa.UniqueConstraint('evaluation_id', 'criterion', name=op.f('uq_uniflow_evaluation_criterion_score_evaluation_id'))
    )
    op.create_index(op.f('ix_uniflow_evaluation_criterion_score_evaluation_id'), 'uniflow_evaluation_criterion_score', ['evaluation_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_uniflow_evaluation_criterion_score_evaluation_id'), table_name='uniflow_evaluation_criterion_score')
    op.drop_table('uniflow_evaluation_criterion_score')
    op.drop_index(op.f('ix_uniflow_submission_file_submission_id'), table_name='uniflow_submission_file')
    op.drop_index(op.f('ix_uniflow_submission_file_file_id'), table_name='uniflow_submission_file')
    op.drop_table('uniflow_submission_file')
    op.drop_index(op.f('ix_uniflow_sponsor_feedback_submission_id'), table_name='uniflow_sponsor_feedback')
    op.drop_index(op.f('ix_uniflow_sponsor_feedback_sponsor_id'), table_name='uniflow_sponsor_feedback')
    op.drop_index(op.f('ix_uniflow_sponsor_feedback_project_id'), table_name='uniflow_sponsor_feedback')
    op.drop_index(op.f('ix_uniflow_sponsor_feedback_milestone_id'), table_name='uniflow_sponsor_feedback')
    op.drop_table('uniflow_sponsor_feedback')
    op.drop_index(op.f('ix_uniflow_advisor_evaluation_submission_id'), table_name='uniflow_advisor_evaluation')
    op.drop_index(op.f('ix_uniflow_advisor_evaluation_student_id'), table_name='uniflow_advisor_evaluation')
    op.drop_index(op.f('ix_uniflow_advisor_evaluation_project_id'), table_name='uniflow_advisor_evaluation')
    op.drop_index(op.f('ix_uniflow_advisor_evaluation_milestone_id'), table_name='uniflow_advisor_evaluation')
    op.drop_index(op.f('ix_uniflow_advisor_evaluation_advisor_id'), table_name='uniflow_advisor_evaluation')
    op.drop_table('uniflow_advisor_evaluation')
    op.drop_index('ix_uniflow_submission_state_time', table_name='uniflow_deliverable_submission')
    op.drop_index(op.f('ix_uniflow_deliverable_submission_team_id'), table_name='uniflow_deliverable_submission')
    op.drop_index(op.f('ix_uniflow_deliverable_submission_submitted_by_id'), table_name='uniflow_deliverable_submission')
    op.drop_index(op.f('ix_uniflow_deliverable_submission_reviewed_by_id'), table_name='uniflow_deliverable_submission')
    op.drop_index(op.f('ix_uniflow_deliverable_submission_project_id'), table_name='uniflow_deliverable_submission')
    op.drop_index(op.f('ix_uniflow_deliverable_submission_deliverable_id'), table_name='uniflow_deliverable_submission')
    op.drop_table('uniflow_deliverable_submission')
    op.drop_index(op.f('ix_uniflow_team_membership_team_id'), table_name='uniflow_team_membership')
    op.drop_index(op.f('ix_uniflow_team_membership_student_id'), table_name='uniflow_team_membership')
    op.drop_index(op.f('ix_uniflow_team_membership_overridden_by_id'), table_name='uniflow_team_membership')
    op.drop_index(op.f('ix_uniflow_team_membership_assigned_by_id'), table_name='uniflow_team_membership')
    op.drop_table('uniflow_team_membership')
    op.drop_index(op.f('ix_uniflow_deliverable_project_id'), table_name='uniflow_deliverable')
    op.drop_index(op.f('ix_uniflow_deliverable_milestone_id'), table_name='uniflow_deliverable')
    op.drop_table('uniflow_deliverable')
    op.drop_index(op.f('ix_uniflow_team_assignment_supersedes_id'), table_name='uniflow_team_assignment')
    op.drop_index(op.f('ix_uniflow_team_assignment_state'), table_name='uniflow_team_assignment')
    op.drop_index(op.f('ix_uniflow_team_assignment_round_id'), table_name='uniflow_team_assignment')
    op.drop_index(op.f('ix_uniflow_team_assignment_project_id'), table_name='uniflow_team_assignment')
    op.drop_index(op.f('ix_uniflow_team_assignment_overridden_by_id'), table_name='uniflow_team_assignment')
    op.drop_index(op.f('ix_uniflow_team_assignment_assigned_by_id'), table_name='uniflow_team_assignment')
    op.drop_index(op.f('ix_uniflow_team_assignment_advisor_id'), table_name='uniflow_team_assignment')
    op.drop_table('uniflow_team_assignment')
    op.drop_index(op.f('ix_uniflow_student_preference_student_id'), table_name='uniflow_student_preference')
    op.drop_index(op.f('ix_uniflow_student_preference_round_id'), table_name='uniflow_student_preference')
    op.drop_index(op.f('ix_uniflow_student_preference_project_id'), table_name='uniflow_student_preference')
    op.drop_table('uniflow_student_preference')
    op.drop_index(op.f('ix_uniflow_project_milestone_template_item_id'), table_name='uniflow_project_milestone')
    op.drop_index(op.f('ix_uniflow_project_milestone_project_id'), table_name='uniflow_project_milestone')
    op.drop_index(op.f('ix_uniflow_project_milestone_owner_id'), table_name='uniflow_project_milestone')
    op.drop_index(op.f('ix_uniflow_project_milestone_accepted_by_id'), table_name='uniflow_project_milestone')
    op.drop_index('ix_uniflow_milestone_state_due', table_name='uniflow_project_milestone')
    op.drop_table('uniflow_project_milestone')
    op.drop_index(op.f('ix_uniflow_meeting_attendee_user_id'), table_name='uniflow_meeting_attendee')
    op.drop_index(op.f('ix_uniflow_meeting_attendee_meeting_id'), table_name='uniflow_meeting_attendee')
    op.drop_table('uniflow_meeting_attendee')
    op.drop_index('ix_uniflow_risk_project_state', table_name='uniflow_risk_issue')
    op.drop_index(op.f('ix_uniflow_risk_issue_resolved_by_id'), table_name='uniflow_risk_issue')
    op.drop_index(op.f('ix_uniflow_risk_issue_reported_by_id'), table_name='uniflow_risk_issue')
    op.drop_index(op.f('ix_uniflow_risk_issue_owner_id'), table_name='uniflow_risk_issue')
    op.drop_index(op.f('ix_uniflow_risk_issue_due_at'), table_name='uniflow_risk_issue')
    op.drop_table('uniflow_risk_issue')
    op.drop_index(op.f('ix_uniflow_report_export_saved_report_id'), table_name='uniflow_report_export')
    op.drop_index(op.f('ix_uniflow_report_export_requested_by_id'), table_name='uniflow_report_export')
    op.drop_index(op.f('ix_uniflow_report_export_file_id'), table_name='uniflow_report_export')
    op.drop_index(op.f('ix_uniflow_report_export_expires_at'), table_name='uniflow_report_export')
    op.drop_index('ix_uniflow_export_state_created', table_name='uniflow_report_export')
    op.drop_table('uniflow_report_export')
    op.drop_index(op.f('ix_uniflow_project_skill_skill_id'), table_name='uniflow_project_skill')
    op.drop_index(op.f('ix_uniflow_project_skill_project_id'), table_name='uniflow_project_skill')
    op.drop_table('uniflow_project_skill')
    op.drop_index(op.f('ix_uniflow_project_objective_project_id'), table_name='uniflow_project_objective')
    op.drop_table('uniflow_project_objective')
    op.drop_index(op.f('ix_uniflow_project_document_project_id'), table_name='uniflow_project_document')
    op.drop_index(op.f('ix_uniflow_project_document_file_id'), table_name='uniflow_project_document')
    op.drop_table('uniflow_project_document')
    op.drop_index('ix_uniflow_notification_queue', table_name='uniflow_notification')
    op.drop_index(op.f('ix_uniflow_notification_project_id'), table_name='uniflow_notification')
    op.drop_index(op.f('ix_uniflow_notification_lock_expires_at'), table_name='uniflow_notification')
    op.drop_index('ix_uniflow_notification_inbox', table_name='uniflow_notification')
    op.drop_index(op.f('ix_uniflow_notification_actor_id'), table_name='uniflow_notification')
    op.drop_table('uniflow_notification')
    op.drop_index(op.f('ix_uniflow_milestone_template_item_template_id'), table_name='uniflow_milestone_template_item')
    op.drop_table('uniflow_milestone_template_item')
    op.drop_index('ix_uniflow_meeting_project_start', table_name='uniflow_meeting')
    op.drop_index(op.f('ix_uniflow_meeting_organizer_id'), table_name='uniflow_meeting')
    op.drop_table('uniflow_meeting')
    op.drop_index('ix_uniflow_audit_target_time', table_name='uniflow_audit_event')
    op.drop_index(op.f('ix_uniflow_audit_event_request_id'), table_name='uniflow_audit_event')
    op.drop_index(op.f('ix_uniflow_audit_event_project_id'), table_name='uniflow_audit_event')
    op.drop_index('ix_uniflow_audit_actor_time', table_name='uniflow_audit_event')
    op.drop_table('uniflow_audit_event')
    op.drop_index(op.f('ix_uniflow_assignment_round_rule_set_id'), table_name='uniflow_assignment_round')
    op.drop_index(op.f('ix_uniflow_assignment_round_initiated_by_id'), table_name='uniflow_assignment_round')
    op.drop_table('uniflow_assignment_round')
    op.drop_index(op.f('ix_uniflow_assignment_criterion_rule_set_id'), table_name='uniflow_assignment_criterion')
    op.drop_table('uniflow_assignment_criterion')
    op.drop_table('uniflow_administrator_bootstrap')
    op.drop_index(op.f('ix_uniflow_user_skill_user_id'), table_name='uniflow_user_skill')
    op.drop_index(op.f('ix_uniflow_user_skill_skill_id'), table_name='uniflow_user_skill')
    op.drop_table('uniflow_user_skill')
    op.drop_index(op.f('ix_uniflow_user_role_user_id'), table_name='uniflow_user_role')
    op.drop_index(op.f('ix_uniflow_user_role_granted_by_id'), table_name='uniflow_user_role')
    op.drop_table('uniflow_user_role')
    op.drop_index('ix_uniflow_exception_user_start', table_name='uniflow_scheduling_exception')
    op.drop_table('uniflow_scheduling_exception')
    op.drop_table('uniflow_scheduling_constraint')
    op.drop_index(op.f('ix_uniflow_saved_report_owner_id'), table_name='uniflow_saved_report')
    op.drop_table('uniflow_saved_report')
    op.drop_index('ix_uniflow_project_status_health', table_name='uniflow_project')
    op.drop_index(op.f('ix_uniflow_project_sponsor_id'), table_name='uniflow_project')
    op.drop_index(op.f('ix_uniflow_project_reviewed_by_id'), table_name='uniflow_project')
    op.drop_index('ix_uniflow_project_lifecycle_deadline', table_name='uniflow_project')
    op.drop_index(op.f('ix_uniflow_project_approved_by_id'), table_name='uniflow_project')
    op.drop_index(op.f('ix_uniflow_project_advisor_id'), table_name='uniflow_project')
    op.drop_table('uniflow_project')
    op.drop_index(op.f('ix_uniflow_milestone_template_family_key'), table_name='uniflow_milestone_template')
    op.drop_index(op.f('ix_uniflow_milestone_template_created_by_id'), table_name='uniflow_milestone_template')
    op.drop_table('uniflow_milestone_template')
    op.drop_index(op.f('ix_uniflow_file_uploaded_by_id'), table_name='uniflow_file')
    op.drop_table('uniflow_file')
    op.drop_index('ix_uniflow_availability_user_day', table_name='uniflow_availability_window')
    op.drop_table('uniflow_availability_window')
    op.drop_index(op.f('ix_uniflow_assignment_rule_set_state'), table_name='uniflow_assignment_rule_set')
    op.drop_index(op.f('ix_uniflow_assignment_rule_set_family_key'), table_name='uniflow_assignment_rule_set')
    op.drop_index(op.f('ix_uniflow_assignment_rule_set_created_by_id'), table_name='uniflow_assignment_rule_set')
    op.drop_table('uniflow_assignment_rule_set')
    op.drop_index('ix_uniflow_user_active_name', table_name='uniflow_user')
    op.drop_table('uniflow_user')
    op.drop_table('uniflow_skill')
    # ### end Alembic commands ###
